### ISSUE TITLE
Create Deal Error

### ISSUE THREAD

**Issue by jonch070** [Ben8t/hubspot-cli#1]
Hello! I get the following error when trying to create a deal after hitting enter after adding deal name

```
🖇️ https://app-eu1.hubspot.com/contacts/45891555/record/0-2/23610107723
🖇️ https://app-eu1.hubspot.com/contacts/45891555/record/0-1/65177433719
Traceback (most recent call last):
  File "/Users/jonathankawchuk/hubspot-tui/tui.py", line 170, in <module>
    tui.launch_menu()
  File "/Users/jonathankawchuk/hubspot-tui/tui.py", line 139, in launch_menu
    self.create_deal()
  File "/Users/jonathankawchuk/hubspot-tui/tui.py", line 60, in create_deal
    deal_stage = self.get_stage()
  File "/Users/jonathankawchuk/hubspot-tui/tui.py", line 128, in get_stage
    stages = [ f'{s.get("stage_id")} - {s.get("label")}' for s in self.hs_client.get_pipeline().get("stages")]
  File "/Users/jonathankawchuk/hubspot-tui/hubspot_client.py", line 97, in get_pipeline
    data = response.json().get("results")[2]
IndexError: list index out of range
```

**Comment by Ben8t** [comment]
Hello @jonch070, can you try by replacing `data = response.json().get("results")[2]`by `data = response.json().get("results")[1]`in line 97 of `hubspot_client.py` ?

Probably something hardcoded on my side to fit with my HS account...

**Comment by jonch070** [comment]
thanks thanks! Changed that line, getting this error again at the same point 


```
🖇️ https://app-eu1.hubspot.com/contacts/45891555/record/0-2/23598200927
🖇️ https://app-eu1.hubspot.com/contacts/45891555/record/0-1/65177989149
Traceback (most recent call last):
  File "/Users/jonathankawchuk/hubspot-tui/tui.py", line 170, in <module>
    tui.launch_menu()
  File "/Users/jonathankawchuk/hubspot-tui/tui.py", line 139, in launch_menu
    self.create_deal()
  File "/Users/jonathankawchuk/hubspot-tui/tui.py", line 60, in create_deal
    deal_stage = self.get_stage()
  File "/Users/jonathankawchuk/hubspot-tui/tui.py", line 128, in get_stage
    stages = [ f'{s.get("stage_id")} - {s.get("label")}' for s in self.hs_client.get_pipeline().get("stages")]
  File "/Users/jonathankawchuk/hubspot-tui/hubspot_client.py", line 97, in get_pipeline
    data = response.json().get("results")[1]
IndexError: list index out of range
```

**Comment by Ben8t** [comment]
Ok was a guess... I'm not really using the CLI at the moment and don't really have time to dig into this one right now :/

So you would better deep dive into yourself, PR welcome 😉  It's probably a matter of checking what's the `response.json()` gives back as response and change the array subset accordingly (`response.json().get("results")[1]`)

**Comment by Ben8t** [comment]
@jonch070 out of curiosity, what's your role and why do you choose to use this CLI?

When I created this piece of code, I was initially thinking it will be only a niche thing that nobody would actually use 😅 but I'm very curious to see you have a need too here. Can you tell me a bit more about your backstory? Also, how did you know about this repository?

**Comment by jonch070** [comment]
Oh for sure! I wish I could say I was a developer and could help out, I actually work as a film composer and I'm just so sick of bloated everything (including clicking around my browser for basic CRM stuff) that I'm trying to do more daily stuff in the terminal with TUIs! So a big sore spot was crm, so trying to find a solution for that, nothing too complex, and doesn't even need to be Hubspot.

Jon

sound | composition
jonathankawchuk.com ( http://jonathankawchuk.com/ )

Sent via Superhuman ( ***@***.*** )

**Comment by Ben8t** [comment]
Ok thanks for the background overview ! So glad a "non-developer" is looking to use TUI :)

Let me got back to this issue during Christmas holidays as my calendar will ligthen a bit so I can work this nerdy stuff!

**Comment by jonch070** [comment]
Ahh thank you! I really appreciate you spending the time on this!!

Jon

sound | composition
jonathankawchuk.com ( http://jonathankawchuk.com/ )

Sent via Superhuman ( ***@***.*** )
